### PR TITLE
Change dataset type from SourceDataset to TargetDataset for return_target_with_labels in get_datasets

### PR DESCRIPTION
**Pull request by deepseek-eoghan**
Made previously discuessed change and added a test ```test_get_mnist_mnistm_target_with_labels```

image

### CODE REVIEW

**Comment by KevinMusgrave** [comment]
Looks good. Maybe ```get_datasets``` should have another keyword flag called ```supervised``` that gets passed to the ```target_train``` and ```target_val``` datasets.

**Comment by deepseek-eoghan** [comment]
I agree, would this be alongside ```return_target_with_labels``` or alongside it?

**Comment by KevinMusgrave** [comment]
I think alongside `return_target_with_labels` because that flag is used in the academic setting where you want to do unsupervised learning, but you want separate target datasets that have the ground truth labels for evaluation.

**Comment by deepseek-eoghan** [comment]
I'm not sure i've added this correctly so you'll need to take a close look at it! :smile: 

Based on my understanding of it.


| supervised? | target_with_labels |                                                             result                                                             |
|-------------|--------------------|--------------------------------------------------------------------------------------------------------------------------------|
| N           | Y                  | target_train, target_val, <- (both unlabeled) target_train_with_labels, target_val_with_labels                                 |
| Y           | N                  | target_train, target_val (both are labeled)                                                                                    |
| Y           | Y                  | target_train, target_val target_train_with_labels, target_val_with_labels (all labeled) [not sure why one would set both true) |
| N           | N                  | target_train, target_val <- (both unlabeled)                                                                                   |

I **think** this is what I have implemented.

I also added a new test ```test_get_mnist_mnistm_supervised```.

I'm sure there will be some changes required so just let me know.

Thanks

**Comment by deepseek-eoghan** [comment]
image

Both tests passing

**Comment by KevinMusgrave** [comment]
Looks good, thanks!

**Pull request merged**
